### PR TITLE
Fixup map server

### PR DESCRIPTION
**Pull request by wjwwood**
@v4hn

### CODE REVIEW

**Comment by mikeferguson** [comment]
@wjwwood Is there something in particular that @v4hn should be noting/reviewing here?

**Comment by wjwwood** [comment]
@mikeferguson he reported it from IRC, I was just letting him know I opened it.

**Comment by mikeferguson** [comment]
Ah ok, LGTM.

**Comment by v4hn** [comment]
On Wed, Sep 03, 2014 at 02:45:18PM -0700, Michael Ferguson wrote:

> @wjwwood Is there something in particular that @v4hn should be noting/reviewing here?

Nah, I just pointed it out, so he added me for reference.

**Comment by DLu** [comment]
Is there a style guide for package.xmls that says messages should go first? (i.e. why was nav_msgs moved?)

**Comment by wjwwood** [comment]
@DLu I didn't remove it, I just alphabetized the list. For longer lists, e.g. rviz, it makes it easier to find a dependency by name.

**Comment by wjwwood** [comment]
Err, I thought you asked why it was _removed_.

**Comment by DLu** [comment]
Nevermind. Let me just go review the alphabet. What comes before N?

**Comment by wjwwood** [comment]
I don't know the alphabet, but my editor does.

**Pull request merged**
