### PR TITLE
[proposed for Kinetic Kame] navfn: change API

### PR DESCRIPTION
**Pull request by hrnr**
this unbounds `NavfnROS` from `Costmap2DROS` allowing its use with just `Costmap2D` without all the `Costmap2DROS` machinery.

Reproposal of #406.

### CODE REVIEW

**Comment by hrnr** [comment]
Hi, how is it going with Kinetic? Is this good to go in?

**Comment by mikeferguson** [comment]
@alexhenning -- can you give your thoughts on this (note that it is Kinetic+ only)

**Comment by alexhenning** [comment]
@mikeferguson SRTM

**Comment by mikeferguson** [comment]
Once previous PR merges pass build, I will merge

**Comment by mikeferguson** [comment]
Current mainline is not building due to https://github.com/ros-planning/navigation/issues/456 -- once we get that resolved this will get in

**Pull request merged**
