### PR TITLE
Fix: Replaced tf2 setEuler calls with setRPY calls

### PR DESCRIPTION
**Pull request by reinzor**
Introduced by https://github.com/ros-planning/navigation/pull/752. Closes https://github.com/ros-planning/navigation/issues/760

### CODE REVIEW

**Comment by mikeferguson** [comment]
Retriggering CI -- not sure why inflation test failed (I've seen it occasionally happen a while ago, but not recently -- so it is still likely unrelated -- we'll see if this passes on second try).

**Comment by mikeferguson** [comment]
heads up to @moriarty

**Review by DLu — APPROVED** [review]

**Comment by moriarty** [comment]
Thanks!

**Comment by mikeferguson** [comment]
This seems to work fine for me -- but my setup is using navfn, so it isn't testing global planner (and thus orientation filter) -- is there someone who has tested this on a robot config that does use orientation filter? (Also, if someone could share which robot config they test with, if it's freely available on Gazebo, I can look at adding it to my manual test suite)

**Comment by moriarty** [comment]
@rayman & @reinzor are you testing this with @ruvu or @tue-robotics stuff? @LoyVanBeek TU/e stuff is available in simulation isn't it?

**Comment by LoyVanBeek** [comment]
I think this is @reinzor's @ruvu stuff cuz' it's vacation time @tue-robotics apparently. And yes, you can test our stuff in simulation, but with a custom [simulator](https://github.com/tue-robotics/fast_simulator).

**Comment by moriarty** [comment]
@mikeferguson, Rein added a comment here:
https://github.com/ros-planning/navigation/pull/752/files/88ada10d9129d529a373162f42fb74cd0821d649#r202910243
(updated link)

**Comment by mikeferguson** [comment]
This is clearly better than the mainline -- and I think the Euler vs. RPY is what is also screwing up #755 as well. After changing those 4 other instances, I've got a working nav stack (in sim, with navfn + base_local_planner)

**Pull request merged**
