### PR TITLE
remove left over PCL depends in dwa_local_planner

### PR DESCRIPTION
**Pull request by mikeferguson**

### CODE REVIEW

**Comment by DLu** [comment]
Part of #264

**Comment by moriarty** [comment]
while this branch is open, navfn/CMakeLists.txt missed a line

**Comment by moriarty** [comment]
It also looks like it's still depended on in costmap_2d but only used in two tests.

**Comment by DLu** [comment]
There's PCL stuff in the two costmap test files, but the static tests PCL line is commented out, and the module_tests isn't currently used, so for the sake of expediency, I'm not converting those.

**Comment by mikeferguson** [comment]
LGTM -- passing CI.

**Pull request merged**
