### PR TITLE
Obstacle layer name is obstacle_layer

### PR DESCRIPTION
**Pull request by LeroyR**
changed clearable_layers_default to obstacle_layer as this is the name used by move_base costmaps

https://github.com/ros-planning/navigation/blob/kinetic-devel/costmap_2d/src/costmap_2d_ros.cpp#L216

### CODE REVIEW

**Comment by DLu** [comment]
Thanks for finding this bug. I haven't tested it myself yet, but I'd rather fix this by changing the backwards-compatible name in costmaps than changing the recovery behavior, since other people may rely on the default configuration of the recovery behavior. What do you think?

**Comment by LeroyR** [comment]
I don't know how many people use either of the current configuration. Could be that other people interact with the obstacle_layer with different plugins or other custom applications.

How about adding both layers to the clearing?

**Comment by DLu** [comment]
I proposed an alternative here: https://github.com/ros-planning/navigation/pull/1005

**Comment by LeroyR** [comment]
#1005 supersedes this, closing this request.

*insert rant about fragmentation of forks after 3 year merge window*

😄

**Comment by DLu** [comment]
The rant would be well deserved.

**Pull request closed without merging**
