### PR TITLE
Increase scope of costmap mutex in publishCostmap to cover costmap calls

### PR DESCRIPTION
**Pull request by griswaldbrooks**

### CODE REVIEW

**Comment by mikeferguson** [comment]
@griswaldbrooks have you tested this with the first path? Where the lock is not normally taken (easiest route would be by setting always_send_full_costmap). I'm pretty sure this is a recursive mutex, but just want to make sure we aren't introducing a deadlock in a different part of the code.

**Comment by griswaldbrooks** [comment]
Sorry to have taken so long in getting back. Yes, it is a recursive mutex https://github.com/ros-planning/navigation/blob/melodic-devel/costmap_2d/include/costmap_2d/costmap_2d.h#L294
I've tested it with the `always_send_full_costmap` set to true.
We've deployed this (and a related fix to our fleet) and had gotten permission to back port this to open source.

**Comment by mikeferguson** [comment]
Also cherry-picked to noetic

**Comment by griswaldbrooks** [comment]
Thanks!

**Pull request merged**
