### PR TITLE
[kinetic] Fix install

### PR DESCRIPTION
**Pull request by DLu**
Working on getting tests to work...

### CODE REVIEW

**Comment by mikeferguson** [comment]
@DLu -- I'd suggest we just remove the travis.yaml file -- travis hasn't been running for like 2 years, since ROS build farm added PR builders. I think something changed in the overall ors-planning org, and now it is firing again.

**Comment by mikeferguson** [comment]
superceded by #843

**Comment by DLu** [comment]
I'm reopening this, because the recovery test requires the files, but they are not installed, so it seems like they should be available.

**Comment by mikeferguson** [comment]
It's not ideal that the tests use resources from other packages, but I guess that's OK since costmap_2d is mostly a library.

**Comment by mikeferguson** [comment]
@DLu please forward port to melodic/lunar. Thx

**Pull request merged**
