### PR TITLE
Remove unnecessary colons

### PR DESCRIPTION
**Pull request by DLu**
Follow up to #201 and #204. Works on my machine at least...

### CODE REVIEW

**Comment by mikeferguson** [comment]
It seems that it would be fine, but I'm not sure why the :: was there in the first place -- @efernandez was there a particular reason to global namespace the hypot calls?

**Comment by efernandez** [comment]
For some reason it didn't work the first time I try with std. I think it was some stupid mistake, because now compiles with std. If it compiles for you as well, go for it.

UPDATE: github's mobile app is quite frustrating... I didn't realized this was already a PR.

**Comment by efernandez** [comment]
:+1: 

FYI I tried with `std::hypot` and that simply fails to compile. With `hypot` is enough (no need for `::hypot`).

**Comment by mikeferguson** [comment]
Ok, that explains how those got there then.

**Pull request merged**
