### PR TITLE
[melodic] moving clearing area method to costmap_layer so other applications can clear other types.

### PR DESCRIPTION
**Pull request by SteveMacenski**
Same as https://github.com/ros-planning/navigation/pull/867 but melodic rebased

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@mikeferguson following up here. I re-targeted this to Melodic

**Comment by SteveMacenski** [comment]
@DLu @mikeferguson  I think this is a reasonable target for Melodic, can we get this merged? It's shifting logic back in to the costmap that should probably be in the costmap anyhow that enables important recoveries in other perception plugins

**Comment by SteveMacenski** [comment]
@DLu I'd appreciate a review / merge :heart: this is blocking https://github.com/SteveMacenski/spatio_temporal_voxel_layer/pull/122

**Comment by mikeferguson** [comment]
LGTM

**Comment by mikeferguson** [comment]
Are you looking for a new release as well I presume?

**Comment by SteveMacenski** [comment]
That would be swell, but no particular rush on timing if you have a normal release cadence. If its more ad-hoc, then I think releasing it soon would be something @MarcelSoler and I would appreciate.

**Comment by mikeferguson** [comment]
Cool - I'd love to have a "normal" release cadence -- we definitely don't. I am hoping to have some time the next few days to make my way through a couple more PRs/issues. I will cut a new release before I leave for ROSCON.

**Comment by SteveMacenski** [comment]
Awesome, well lets chat in china! I'll be the idiot wearing a sling (from falling off a motorcycle on the 101). 

If there's any tickets / PRs in particular you want help on also feel free to ping me.

**Comment by MarcelSoler** [comment]
Nice! I'll test it as soon as I can.

**Pull request merged**
