### PR TITLE
Use boost::shared_array for memory allocations to fix memory leaks (fix #118)

### LINKED ISSUE #118: Possible memory corruption in costmap_2d (hydro)
I debugged our move_base variant using the costmap_2d package with valgrind in hydro, as we have a strange bug that has to do with memory corruption. Although I am not sure if this is related to our bug, valgrind reports some "Conditional jump or move depends on uninitialised value(s)" and "Use of uninitialised value of size 8" errors during the construction of the `Costmap2DROS` instance:

```
Conditional jump or move depends on uninitialised value(s)
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: costmap_2d::InflationLayer::computeCaches() in /opt/ros/hydro/lib/liblayers.so
  2: costmap_2d::InflationLayer::reconfigureCB(costmap_2d::InflationPluginConfig&, unsigned int) in /opt/ros/hydro/lib/liblayers.so
  3: costmap_2d::InflationLayer::onInitialize() in /opt/ros/hydro/lib/liblayers.so
  4: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  5: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  6: main in src/hector_move_base.cpp:510

Conditional jump or move depends on uninitialised value(s)
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: costmap_2d::InflationLayer::computeCaches() in /opt/ros/hydro/lib/liblayers.so
  2: costmap_2d::InflationLayer::matchSize() in /opt/ros/hydro/lib/liblayers.so
  3: costmap_2d::InflationLayer::onInitialize() in /opt/ros/hydro/lib/liblayers.so
  4: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  5: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  6: main in src/hector_move_base.cpp:510

Use of uninitialised value of size 8
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: __ieee754_exp_sse2 in /build/buildd/eglibc-2.15/math/../sysdeps/ieee754/dbl-64/e_exp.c:88
  2: costmap_2d::InflationLayer::computeCaches() in /opt/ros/hydro/lib/liblayers.so
  3: costmap_2d::InflationLayer::matchSize() in /opt/ros/hydro/lib/liblayers.so
  4: costmap_2d::InflationLayer::onInitialize() in /opt/ros/hydro/lib/liblayers.so
  5: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  6: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  7: main in src/hector_move_base.cpp:510

Conditional jump or move depends on uninitialised value(s)
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: exp in /build/buildd/eglibc-2.15/math/../sysdeps/ieee754/dbl-64/w_exp.c:32
  2: costmap_2d::InflationLayer::computeCaches() in /opt/ros/hydro/lib/liblayers.so
  3: costmap_2d::InflationLayer::matchSize() in /opt/ros/hydro/lib/liblayers.so
  4: costmap_2d::InflationLayer::onInitialize() in /opt/ros/hydro/lib/liblayers.so
  5: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  6: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  7: main in src/hector_move_base.cpp:510

Conditional jump or move depends on uninitialised value(s)
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: costmap_2d::calculateMinAndMaxDistances(std::vector<geometry_msgs::Point_<std::allocator<void> >, std::allocator<geometry_msgs::Point_<std::allocator<void> > > > const&, double&, double&) in /opt/ros/hydro/lib/libcostmap_2d.so
  2: costmap_2d::LayeredCostmap::setFootprint(std::vector<geometry_msgs::Point_<std::allocator<void> >, std::allocator<geometry_msgs::Point_<std::allocator<void> > > > const&) in /opt/ros/hydro/lib/libcostmap_2d.so
  3: costmap_2d::Costmap2DROS::readFootprintFromString(std::string const&) in /opt/ros/hydro/lib/libcostmap_2d.so
  4: costmap_2d::Costmap2DROS::readFootprintFromParams(ros::NodeHandle&) in /opt/ros/hydro/lib/libcostmap_2d.so
  5: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  6: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  7: main in src/hector_move_base.cpp:510

Conditional jump or move depends on uninitialised value(s)
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: costmap_2d::Costmap2DROS::reconfigureCB(costmap_2d::Costmap2DConfig&, unsigned int) in /opt/ros/hydro/lib/libcostmap_2d.so
  2: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  3: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  4: main in src/hector_move_base.cpp:510

153 (72 direct, 81 indirect) bytes in 1 blocks are definitely lost in loss record 2,325 of 3,290
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: operator new[](unsigned long) in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: costmap_2d::InflationLayer::computeCaches() in /opt/ros/hydro/lib/liblayers.so
  3: costmap_2d::InflationLayer::matchSize() in /opt/ros/hydro/lib/liblayers.so
  4: costmap_2d::InflationLayer::onInitialize() in /opt/ros/hydro/lib/liblayers.so
  5: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  6: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  7: main in src/hector_move_base.cpp:510

153 (72 direct, 81 indirect) bytes in 1 blocks are definitely lost in loss record 2,326 of 3,290
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: operator new[](unsigned long) in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: costmap_2d::InflationLayer::computeCaches() in /opt/ros/hydro/lib/liblayers.so
  3: costmap_2d::InflationLayer::reconfigureCB(costmap_2d::InflationPluginConfig&, unsigned int) in /opt/ros/hydro/lib/liblayers.so
  4: costmap_2d::InflationLayer::onInitialize() in /opt/ros/hydro/lib/liblayers.so
  5: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  6: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  7: main in src/hector_move_base.cpp:510

720 (72 direct, 648 indirect) bytes in 1 blocks are definitely lost in loss record 2,795 of 3,290
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: operator new[](unsigned long) in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: costmap_2d::InflationLayer::computeCaches() in /opt/ros/hydro/lib/liblayers.so
  3: costmap_2d::InflationLayer::reconfigureCB(costmap_2d::InflationPluginConfig&, unsigned int) in /opt/ros/hydro/lib/liblayers.so
  4: costmap_2d::InflationLayer::onInitialize() in /opt/ros/hydro/lib/liblayers.so
  5: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  6: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  7: main in src/hector_move_base.cpp:510

720 (72 direct, 648 indirect) bytes in 1 blocks are definitely lost in loss record 2,796 of 3,290
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: operator new[](unsigned long) in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: costmap_2d::InflationLayer::computeCaches() in /opt/ros/hydro/lib/liblayers.so
  3: costmap_2d::InflationLayer::matchSize() in /opt/ros/hydro/lib/liblayers.so
  4: costmap_2d::InflationLayer::onInitialize() in /opt/ros/hydro/lib/liblayers.so
  5: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  6: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  7: main in src/hector_move_base.cpp:510

1,048,576 bytes in 1 blocks are definitely lost in loss record 3,274 of 3,290
  in hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  1: operator new[](unsigned long) in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: costmap_2d::Costmap2D::initMaps(unsigned int, unsigned int) in /opt/ros/hydro/lib/libcostmap_2d.so
  3: costmap_2d::Costmap2D::resizeMap(unsigned int, unsigned int, double, double, double) in /opt/ros/hydro/lib/libcostmap_2d.so
  4: costmap_2d::ObstacleLayer::onInitialize() in /opt/ros/hydro/lib/liblayers.so
  5: costmap_2d::Costmap2DROS::Costmap2DROS(std::string, tf::TransformListener&) in /opt/ros/hydro/lib/libcostmap_2d.so
  6: hector_move_base::HectorMoveBase::HectorMoveBase(std::string, tf::TransformListener&) in src/hector_move_base.cpp:27
  7: main in src/hector_move_base.cpp:510
```

I am aware that this output is not very useful without a debug build of costmap_2d.  Duplicate entries have been removed. I did not try to build costmap_2d in debug mode yet to get more details in the traces, but perhaps there is an obvious error. From the above output and the code in `inflation_layer.cpp` it seems that `computeCaches()` is called more than once with some uninitialized input variables without calling `deleteKernels()` in-between to free the reserved memory.

Could costmap_2d be also responsible for the memory corruption in our own code? The class instance with the corrupted data members is allocated directly after the Costmap2DROS instance in our code.

I am using ros-hydro-costmap-2d version 1.11.3-0precise-20130820-1008-+0000.

### PR DESCRIPTION
**Pull request by meyerj**

### CODE REVIEW

**Comment by DLu** [comment]
For the unknowledgeable in the ways of boost, can you briefly describe what advantage the shared_array has?

**Comment by meyerj** [comment]
@DLo `shared_array` is the equivalent of a `shared_ptr` for arrays allocated with `new[]`. These smart pointers keep track internally of how often they have been copied and automatically call `delete` (or `delete[]` in the case of a `shared_array`) if there is no reference to the allocated memory anymore. Basically they just save you from keeping track of all memory allocated with `new` in order to free it properly using `delete`. See http://www.boost.org/doc/libs/1_54_0/libs/smart_ptr/smart_ptr.htm for reference.

Basically 8fd6a49bbd7221683323f8b5c9aad5f03ad851e6 just replaces the pointers by `shared_array`s and therefore ensures that no memory is lost over time. In the original version `InflationLayer::computeCaches()` just allocates new memory and eventually overwrites the pointer to the previous allocation. `InflationLayer::deleteKernels()` was only called once in the destructor. Even if you would add `deleteKernels()` each time you call `computeCaches()` you would have to make sure that `cell_inflation_radius_` has not changed since the last call to `computeCaches()`. The same holds for `Costmap2D::initMaps()` and `Costmap2D::deleteMaps()`.

`shared_array` just does that book-keeping auto-magically without having to bother too much. If the static map is really static, this leak might be neglectable, but in the dynamic map case with frequent `resizeMap()` calls and without the patch from #120 memory consumption of move_base on low-memory machines might be an issue.

**Comment by meyerj** [comment]
Should I revert a678e17c758a33c8c6c185137a6a2b03ad52a344 before an eventual merge as it had obviously nothing to do with the memory leak? I am sorry.

**Comment by DLu** [comment]
Sorry for the slow response. I'll be a little more free after the ICRA deadline.

**Comment by meyerj** [comment]
I rebased the commits on the latest HEAD revision in hydro-devel.

I am not sure, if the memory leak problem in costmap_2d still persists, as there are some new checks in `void InflationLayer::computeCaches()` since 6532c847d7ef3ee828b38cc6d3ac757ae4790906. I will try during the next days and close this pull request if the problem has already been solved.

Independent of the memory leak I would still say that the shared_arrays are safer and make the code more readable for little costs.

**Comment by mikeferguson** [comment]
This is no longer merge-able and discussion has died off, please reopen a new PR if this is still relevant.

**Pull request closed without merging**
