### PR TITLE
Fix indexing bug in OccupancyGridUpdate callback function

### PR DESCRIPTION
**Pull request by Julse**
Wrong indexing for updated costmap area.

### CODE REVIEW

**Comment by mikeferguson** [comment]
How does this even compile? I don't see where size_x comes from

**Comment by Julse** [comment]
Hi,
you're right. It was supposed to be 'size_x_', which is the size of the costmap in x direction. 
I changed it.

**Comment by mikeferguson** [comment]
@DLu wanta take a look at this?

**Comment by DLu** [comment]
+1

**Pull request merged**
