### PR TITLE
Check NULL before deleting costmap

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by mikeferguson** [comment]
costmap_ = NULL was already added in #277. Deletion of NULL is OK based on C++ spec.

**Comment by garaemon** [comment]
Oh, I don't know the C++ spec.
But i had this problem with  safe_teleop_base.
I will send gdb log about this problem

2014年12月10日水曜日、Michael Fergusonnotifications@github.comさんは書きました:

> Closed #291 https://github.com/ros-planning/navigation/pull/291.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-planning/navigation/pull/291#event-205317409.

## 

from iPhone

**Comment by mikeferguson** [comment]
@garaemon You will also want to pull the latest code -- because I said we fixed the =NULL part, but that doesn't appear to be part of your branch.

**Comment by garaemon** [comment]
!!
I will check it out soon!

2014年12月11日木曜日、Michael Fergusonnotifications@github.comさんは書きました:

> @garaemon https://github.com/garaemon You will also want to pull the
> latest code -- because I said we fixed the =NULL part, but that doesn't
> appear to be part of your branch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-planning/navigation/pull/291#issuecomment-66522943
> .

## 

from iPhone

**Pull request closed without merging**
