### PR TITLE
Allow specification of free/occupied thresholds for map_saver (#708)

### PR DESCRIPTION
**Pull request by mikeferguson**
* add occupied threshold command line parameter to map_saver (--occ)
* add free threshold command line parameter to map_saver (--free)

### CODE REVIEW

**Comment by mikeferguson** [comment]
@ipa-fez @allenh1 -- in forward porting #708 -- I realized we had a partial fix for this in #613 -- I've tried to merge them together -- if you have a chance to comment on this, please do.

**Comment by ipa-fez** [comment]
Looks good to me :+1:

**Review by allenh1 — APPROVED** [review]
lgtm -- this is definitely a more robust way to do it!

**Comment by mikeferguson** [comment]
Thanks guys! -- I'll merge this in the morning and do the back port to lunar at that time.

**Comment by mikeferguson** [comment]
And by "in the morning", I apparently meant "two weeks from now"

**Pull request merged**
