### PR TITLE
Added planner_overclock_ratio param to move_base

### PR DESCRIPTION
**Pull request by KaijenHsiao**
This param times the planner_frequency is the new frequency for the planning loop.  At this frequency, it checks if a new plan is needed based on a new goal or a stuck controller (or if it's time to plan again based on the old planner_frequency).

This eliminates the problem where you ask the robot to go to a new location, or the controller is unable to execute the plan, and instead of replanning, the robot stops and waits for the next planner loop (at a potentially very slow planner_frequency).

(Thanks to Sachi Hemachandra.)

### CODE REVIEW

**Comment by mikeferguson** [comment]
@DLu do you have any thoughts on this PR?

@KaijenHsiao is there possibly a better name than "planner_overclock_ratio"?

**Comment by KaijenHsiao** [comment]
I'm sure there is. :)  Do you have any suggestions?  
I thought it should be something like check_replan_needed_planner_frequency_multiplier, but, um, shorter.  But I couldn't think of anything good.

**Comment by DLu** [comment]
So the MoveBase planning logic is a mess, and I'm hoping to finish up some changes and refactoring soon. 

I think the behavior you want can be accomplished by calling planner_cond_.notify_one(), which the code already does here. It's entirely possible that this doesn't happen in practice, but I think that it should happen. Does this reflect what you've seen?

**Comment by KaijenHsiao** [comment]
If I understand correctly, calling planner_cond_.notify_one() only does something useful if your planner_frequency is set to 0.  If you want the planner to run by default at a given slow frequency (such as 0.2 Hz), then calling planner_cond_.notify_one() does not help, since it is still sleeping for 1/planner_frequency seconds before trying to plan again.

**Comment by KaijenHsiao** [comment]
Replaced by #282.

**Pull request closed without merging**
