### PR TITLE
Switch to tf2

### PR DESCRIPTION
**Pull request by vrabaud**
This is a replacement for indigo of https://github.com/ros-planning/navigation/pull/298, which was for hydro.

### CODE REVIEW

**Comment by vrabaud** [comment]
All the fixes needed upstream to get that code to compile went through but you still need those two merge requests to get tests to pass:
- [x] https://github.com/ros/geometry_experimental/pull/79
- [x] https://github.com/ros/geometry_experimental/pull/83

**Comment by vrabaud** [comment]
and btw, the main motivation for tf2 is to remove the PCL dependency (which will be the next merge request : https://github.com/vrabaud/navigation/commit/28b39815243d12ad5b7499482ecc5b1977cf31cc )

**Comment by vrabaud** [comment]
should I close that pull request and re-open it for Jade only ?

**Comment by mikeferguson** [comment]
We can leave this one open -- but please open a PR for Jade and then if we end up backporting we will already have this PR for the backport to indigo.

**Comment by mikeferguson** [comment]
@vrabaud with PR79 merged, 83 looks like it is only for bag files -- this is probably ready for on-robot testing? If so I'll get one my folks to test it out.

**Comment by vrabaud** [comment]
indeed, go ahead !

**Comment by vrabaud** [comment]
I had to make a few more commits because of some build failures when cherry-picking for Jade. Nothing major, it's all good to go but I have to say that the amcl tests do not pass on Jade...

**Comment by vrabaud** [comment]
I had forgotten to install a Python package .... everything's fine and cherry-pickable for jade on my side.

**Comment by vrabaud** [comment]
all the upstream bugs in tf2 got fixed. Have you guys had time to test ? I just rebased.
I know it's a scary change but if you just look line by line, you'll see the changes are pretty trivial at 95%.
We can also just focus on Jade of course.

**Comment by vrabaud** [comment]
Let's just focus on Jade and #322

**Pull request closed without merging**
