### PR TITLE
revert #410, add optional timeout to avoid deadlock

### PR DESCRIPTION
**Pull request by mikeferguson**

### CODE REVIEW

**Comment by mikeferguson** [comment]
Addresses #432 #430

@mirzashah @ssrselvamraju I'm unable to figure out why this causes what you're reporting -- I have something else occurring on our robots that is maybe related, but I'm unable to reproduce your exact bug described. I'm going to roll back the change and add an optional param to limit the time we can get stuck if someone is using two static costmap layers

**Comment by ssrselvamraju** [comment]
@mikeferguson I can send you some bag files if you'd like to review.

**Comment by mirzashah** [comment]
@mikeferguson sorry i've been out of the loop and trying to catch up on this -- I'll make a note to try this version out and see if it causes the same issue

**Comment by ssrselvamraju** [comment]
@mikeferguson Just a heads up - I tested this commit on one of our robots, and didn't seem to have fixed the issue. I'm testing more on other machines, with different configurations. Will update details soon.

**Comment by mikeferguson** [comment]
closed in favor of #446

**Pull request closed without merging**
