### PR TITLE
WIP: [AMCL] Fix map import & particle filter bugs and augmented with some debug info & utility

### PR DESCRIPTION
**Pull request by alicegong**
**WIP**: Retargeting lunar and seprating changes into individual commits according to discussion in #680 

> - Added to check orientation included in map_msg.info to rotate map upon import (originally assume to discard this info!)
> - Dissected its source code to locate procedures _not_ implemented as proposed in _"Probabilistic Robotics"_,
> - Rewrote its adaptive sampling procedures to appropriately adjust sample size according to state uncertainty,
> - Replaced its uniform re-sampling procedures with weighted re-sampling, enabling consistent convergence,
> - Fixed its problematic bias in calculation of particle posterior probability against unknown areas on map, 
> - Modified sensor measurement model - behaviour during in-place rotation,
> - Implemented an augmentation on an another thread to listen to odometry & extrapolate between pose update using odometry (uses/requires MRPT, turn it on with cmake option BUILD_EXTRAPOLATION)
> - Improved estimation accuracy and consistency by at least 5x, validated error margins to be within 10cm for over 10m travelled in real environments 🎆  .

TO-DOs
----
- [x] purely sync up the indentations: up to [e05c03e](https://github.com/ros-planning/navigation/pull/716/commits/e05c03e506cd8342df69ded8da946ca2446ecf47)
- [ ] pure refactor (into functions/class/etc)
- [ ] more refactor (the ones that were refactor into different files)
- [ ] build system update (may be combined with above if not too much?)
- [ ] each specific change in bullet points I listed (in as much isolation as possible)

### CODE REVIEW

**Comment by alicegong** [comment]
Purely sync up the indentations
---
- [x] map: [fce7c65](https://github.com/ros-planning/navigation/pull/716/commits/fce7c653e6ff97d4946a687cf2a4576462aa1434) [Build Status](http://build.ros.org/job/Lpr__navigation__ubuntu_xenial_amd64/49/)
- [x] pf: [ebe8873..9c1c016](https://github.com/ros-planning/navigation/pull/716/files/fce7c653e6ff97d4946a687cf2a4576462aa1434..9c1c016c72ddb453c74f278b0b7f5db60ea8d231) [Build Status](http://build.ros.org/job/Lpr__navigation__ubuntu_xenial_amd64/52/)
- [x] sensors: [b7d5db5..b39c5a7](https://github.com/ros-planning/navigation/pull/716/files/9c1c016c72ddb453c74f278b0b7f5db60ea8d231..b39c5a7c9ddb69fd9a183f0f02139292d429fd88) [Build Status](http://build.ros.org/job/Lpr__navigation__ubuntu_xenial_amd64/60/)
- [x] 2 spaces for soft tab: [dfba53e](https://github.com/ros-planning/navigation/pull/716/commits/dfba53e5b02d90d49f4d234c2b676d09aae1349a)
- [x] amcl_node: [2cf76f1..e05c03e](https://github.com/ros-planning/navigation/pull/716/files/b39c5a7c9ddb69fd9a183f0f02139292d429fd88..e05c03e506cd8342df69ded8da946ca2446ecf47) [Build Status](http://build.ros.org/job/Lpr__navigation__ubuntu_xenial_amd64/64/)

**Comment by alicegong** [comment]
@mikeferguson btw, as I am working on this, what are your thought on converting AMCL stuffs written in C into C++? There seems to be some pointers floating around so memory loss...

**Comment by alicegong** [comment]
Pure refactor (into functions/class/etc)
---
- [ ] map
> - [ ] variables (specifically, declaration and assignment should be paired up, for loop indices should be declared in for statement)  [Build Status](http://build.ros.org/job/Lpr__navigation__ubuntu_xenial_amd64/65/)
> - [ ] clean up from post to pre-increments [Build Status](http://build.ros.org/job/Lpr__navigation__ubuntu_xenial_amd64/68/)
> - [ ] distances as a vector, rather than pointer of floats manually allocated [Build Status](http://build.ros.org/job/Lpr__navigation__ubuntu_xenial_amd64/67/)
- [ ] pf
- [ ] sensors

**Comment by AchmadFathoni** [comment]
Is there any plan for melodic-dev branch?

**Comment by alicegong** [comment]
> Is there any plan for melodic-dev branch?

Is this the branch I should be targeting now instead of lunar?

**Comment by AchmadFathoni** [comment]
Actually I am not the  official maintainer of this repository so I can't decide. 

But this is the idea: Melodic is LTS and Lunar is not, and people tend to pay more attention to LTS release.

**Comment by AchmadFathoni** [comment]
And comparing your PR to newer but accepted PR, I conclude this repository maintainers are faster merging PR that short and has few purpose than the opposite. 

So maybe if you have plan to make PR for melodic branch you  should divide the PR for each distinct  TO-DOs. 

After all I believe your idea in this PR will be useful for people.

**Comment by alicegong** [comment]
> And comparing your PR to newer but accepted PR, I conclude this repository maintainers are faster merging PR that short and has few purpose than the opposite.
> 
> So maybe if you have plan to make PR for melodic branch you should divide the PR for each distinct TO-DOs.
> 
> After all I believe your idea in this PR will be useful for people.

Fair point but I feel that it'll end up needing ~10 PR? I'm really unsure what the best way to go about this is.

**Comment by alicegong** [comment]
> Actually I am not the official maintainer of this repository so I can't decide.
> 
> But this is the idea: Melodic is LTS and Lunar is not, and people tend to pay more attention to LTS release.

Right. But maintainers said LTS shouldn't include "experimental" stuffs - changes this significant make it kind of experimental because it hasn't been tested by lots of robots out there.

**Comment by AchmadFathoni** [comment]
@alicegong well I thought your PR is well tested in the first place. I still not know what is the line that divide experimental and stable PR.

**Comment by alicegong** [comment]
@AchmadFathoni It was well tested on the platform we were developing in the use case situation that the product was developed for. I'm not sure if that makes it stable enough to go into a LTS? Maybe @mikeferguson can tell us?

**Comment by AchmadFathoni** [comment]
Finish reading Probabilistic Robotic.  After clarifying my understanding by learning amcl source code I will try to translate this PR into kinetic branch.

**Comment by alicegong** [comment]
Yes please help! I’m stuck at a broken unit test written in Python that AMCL code doesn’t even touch...

**Comment by AchmadFathoni** [comment]
Each of your commit inside your PR #680 and #761 is sure big and contain lot of changes. I believe I need your help. Lets start with first point,  how map orientation will help amcl? As far I know, is the amcl job to figure out robot's orientation inside map regardless map orientation itself.

**Comment by AchmadFathoni** [comment]
My plan is to make a branch for each point inside bullet list above. I believe it will be more efficient if I ask you directly rather than analyzing each line in your commit. 

Lets start with first bullet point. How map rotation information will help amcl? As far I know,  is the amcl to figure out robot's orientation inside map regardless map's orientation itself.

**Comment by AchmadFathoni** [comment]
@alicegong My plan is to make a branch for each point inside feature list above. I believe it will be more efficient to ask you about explanation of your source code rather than analyzing 9000 lines in your PR's commit. So lets start with first point, how map orientation information will help amcl? As far I know, is the amcl job to figure out robot's orientation inside map regardless the map orientation itself.

**Comment by alicegong** [comment]
@AchmadFathoni I only just realized you made new comments here. Yes it IS amcl's job to figure out robot's orientation inside the map regardless the map orientation. However, when the map is first loaded, the cells are read and indexed assuming a certain orientation. Even if the map file wrote that the orientation is not as assumed. Now the indexing through all the grid cell for all the remaining calculations are off. Look at `int rotateIndex(int rotate90x, int i, int j, size_t leni, size_t lenj)` and `int AmclNode::setMapSpecs( const nav_msgs::OccupancyGrid& map_msg, map_t* map )` in `amcl_node.hpp` in this PR and you may see what I mean.

**Comment by jcmonteiro** [comment]
Hey, @alicegong. Maybe it would be better if you removed all the changes related to code formatting. These changes are not related to the PR, can delay the review process, and produce conflicts with changes in other branches.

**Comment by alicegong** [comment]
> Hey, @alicegong. Maybe it would be better if you removed all the changes related to code formatting. These changes are not related to the PR, can delay the review process, and produce conflicts with changes in other branches.

im joining the ROS2 working group to work on localization there instead. will try to incorporate the fixes for problems I saw in here if possible.

**Comment by mikeferguson** [comment]
Targets a dead release (lunar). If this is still of interest, please open a PR to noetic-devel branch

**Pull request closed without merging**
