### PR TITLE
Use hypot(x, y) instead of sqrt(x*x, y*y)

### PR DESCRIPTION
**Pull request by efernandez**
This follows #184

`amcl` not covered because it fails to find `#include <cmath>`.

### CODE REVIEW

**Comment by mikeferguson** [comment]
@efernandez This is breaking tests: http://jenkins.ros.org/job/devel-indigo-navigation/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/4/testReport/

**Comment by mikeferguson** [comment]
@efernandez Hydro seems to have even more failed tests: http://jenkins.ros.org/job/devel-hydro-navigation/16/testReport/

**Comment by efernandez** [comment]
@mikeferguson I've been investigating this with @bmagyar, looking into the `cmath` library. The tests also fail in my machine (sorry for not testing). Apparently, `hypot(x, y)` and `sqrt(x*x, y*y)` are not completely equivalent in practice, because of the numeric precision. In theory it should be the same (http://en.cppreference.com/w/cpp/numeric/math/hypot), but I'm not a 100% sure because of two factors:
- At the end, the `hypot` code is different to `sqrt(x*x, y*y)`, although I haven't seen the code; this is all that I've seen from Boost (http://www.boost.org/doc/libs/1_34_1/doc/html/boost_math/math_special_functions.html#boost_math.math_special_functions.hypot), which I think it was moved to the standard. There's also this reference pseudo-code: http://en.wikipedia.org/wiki/Hypot#Implementation, and some articles covering how to implement `sqrt(x*x + y*y)` safely: http://www.johndcook.com/blog/2010/06/02/whats-so-hard-about-finding-a-hypotenuse/
- It might be a bug (I don't think so) or a setting (it could be) that makes `hypot` use `long double` even for `double` input arguments.

I see two options here:
- Revert this PR
- Update the tests (if they're right) with the new results using `hypot`.

**Comment by efernandez** [comment]
BTW, there were 4 cases were I used `hypot` instead of `hypotf`, which should be the replacement for `sqrtf`. However, I've tried that and the tests still fail; I tested with `rostest costmap_2d obstacle_tests.launch` only.

**Comment by mikeferguson** [comment]
I actually think the tests are suspect. In particular https://github.com/ros-planning/navigation/blob/hydro-devel/costmap_2d/test/obstacle_tests.cpp#L90 should set the diagonal to be LETHAL (254), right?

This is the final map (i added printmap at L95) under the old code:

```
   0   0   0   0   0   0   0 254 254 254

   0   0   0   0   0   0   0 254 254 254

   0   0   0 254 254 254   0   0   0   0

   0   0   0   0   0   0   0   0   0   0

   0   0   0   0   0   0   0   0   0   0

   0   0   0   0 254   0   0 254 254 254

   0   0   0   0 254   0   0 254 254 254

   0   0   0   0   0   0   0 254 254 254

   0   0   0   0   0   0   0   0   0   0

   0   0   0   0   0   0   0   0   0 254
```

0,0 is the upper left, 9,9 is lower right. And the new code looks like:

```
   0   0   0   0   0   0   0 254 254 254

   0 254   0   0   0   0   0 254 254 254

   0   0 254 254 254 254   0   0   0   0

   0   0   0 254   0   0   0   0   0   0

   0   0   0   0 254   0   0   0   0   0

   0   0   0   0 254 254   0 254 254 254

   0   0   0   0 254   0 254 254 254 254

   0   0   0   0   0   0   0 254 254 254

   0   0   0   0   0   0   0   0 254   0

   0   0   0   0   0   0   0   0   0 254
```

I have no idea why the old code doesn't fill in the diagonal, nor why the new code does, nor has this test been changed in quite some time.

@DLu any ideas? You're the author on these tests it looks like.

**Comment by efernandez** [comment]
@mikeferguson @DLu For me this test also looks strange; I mean, I don't see why `with_static` should be equal to `obs_after`, if the diagonal is filled in with new `LETHAL` values.
Furthermore, shouldn't the cell `<0, 0>` be marked as `LETHAL (254)`?
I don't really understand what the `layers.updateMap(0,0,0);` instruction does?

**Comment by mikeferguson** [comment]
Anybody have any further thoughts on this? We should probably put a release out to include #202, but I'm not sure if we should revert this, or actually need to fix the tests (and can do that later).

**Comment by mikeferguson** [comment]
@efernandez Tracked this down. PR to fix is here: https://github.com/ros-planning/navigation/pull/204 I'm going to wait until the current devel test finishes before merging so that I can get separate tests on the farm. Basically, the issue here was that subtraction of unsigned numbers was causing the hypot to be wrong. I added static_casts to force everything to doubles.

I've also added numerous comments in the tests, which turned out be correct, but the logic of why was fairly involved.

**Comment by efernandez** [comment]
Nice catch @mikeferguson !

**Comment by DLu** [comment]
What is the logic behind the ::hypot notation? To me the two colons seem clunky.

**Comment by efernandez** [comment]
@DLu I guess ``std::hypot` failed with my compiler... but I've just tried in another computer and it works.
Therefore, I agree on using `std::hypot` instead: here and also for #184

**Pull request merged**
