### PR TITLE
Break infinite loop when tolerance 0 is used

### PR DESCRIPTION
**Pull request by v4hn**
With an increment of 0, there wouldn't be an increment...

### CODE REVIEW

**Comment by mikeferguson** [comment]
Tests failing after merge -- not sure why exactly, but the greenroom loop test is timing out: http://jenkins.ros.org/job/devel-indigo-navigation/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/61/ all other tests have runtimes nearly the same as before.

**Comment by v4hn** [comment]
Heya, thanks for the quick handling of the request.

I just had a look at the test and it does not have _anything_ to do with move_base
as far as I can see. I'm therefore pretty confident that this is independent of
my bugfix.

**Comment by mikeferguson** [comment]
Yeah, it seemed pretty suspect as being not related to the PR. I've kicked the farm to rerun tests to see if it was actually a farm failure (because the test completes on my local desktop)

**Comment by mikeferguson** [comment]
Yup, back to stable -- must have been an issue with the farm

**Pull request merged**
