### PR TITLE
Fixes uninitialised variable 'combination_method'

### LINKED ISSUE #187: static layer sometimes doesn't use map to create the global costmap
Sometimes, the static layer doesn't create the global costmap properly, creating only an empty costmap. 

To exemplify, this is the map being published:

screenshot from 2014-04-28 17 44 24

This is the global costmap when the static layer doesn't load the map properly

screenshot from 2014-04-28 17 44 51

If you try to relaunch, it loads the map properly, and you have the following global costmap:

screenshot from 2014-04-28 17 45 09

This problem seems to only appear the first time you try to launch navigation, after that it looks like it always creates the global costmap properly

### PR DESCRIPTION
**Pull request by stonier**
This will close #187, refer to the discussion there for details.

### CODE REVIEW

**Comment by mikeferguson** [comment]
@stonier Does combination_method == 0 actually work? It isn't clear from the other ticket if == 0 works at all. If it doesn't work, we probably should not even expose it in dynamic reconfigure for now.

**Comment by stonier** [comment]
`combination_method == 0` is a complete failure. The obstacle (voxel) layer coming in on the first iteration will completely write over the whole map with zeroes everywhere except for locally sensed obstacles, resulting in what @BFALacerda posted:

global_costmap

**Comment by stonier** [comment]
> we probably should not even expose it in dynamic reconfigure for now.

Yeah, hard coding it was one of the options I posed in #187. Are there use cases where you use a VoxelLayer without a StaticLayer though? This problem here is specific to the case where you have a StaticLayer underneath the VoxelLayer (i.e. typical global_costmap configuration).

**Comment by mikeferguson** [comment]
I just noticed this is actually a change in voxel layer, not static layer. In which case, there may actually be a reason to overwrite in some other use cases. This PR will fix it for most users and still allow the other option for those that desire it. LGTM.

**Comment by mikeferguson** [comment]
I'll get a new release out into hydro/indigo as soon as we sort out the test issues of #201

**Pull request merged**
