### PR TITLE
uncommented trajectory_planner_ros from catkin_package LIBRARIES so other packages can find it

### PR DESCRIPTION
**Pull request by KaijenHsiao**

### CODE REVIEW

**Comment by jonbinney** [comment]
+1

**Comment by DLu** [comment]
I was bad and didn't test this before merging. Did this compile for you when you made the change?

**Comment by mikeferguson** [comment]
@DLu are you seeing an error? Trunk compiled for me the other day.

**Comment by jonbinney** [comment]
compiled for me as well

**Comment by DLu** [comment]
Ok, I clearly just broke something on my machine.

**Pull request merged**
