### PR TITLE
multipling cost by a factor

### PR DESCRIPTION
**Pull request by tavu**
fixing issue #357

### CODE REVIEW

**Comment by mikeferguson** [comment]
@DLu please review

**Comment by DLu** [comment]
This highlights some oversights in how the code was refactored, so thank you for that. However, it introduces a couple additional inconsistencies to where factor is applied. 

I'm not sure why I put it there, but the costs should go through the getCost function (https://github.com/ros-planning/navigation/blob/jade-devel/global_planner/include/global_planner/dijkstra.h#L86) that's in dijkstra.h. 

I'll add a few more comments later, and possibly a pull request of my own.

**Comment by DLu** [comment]
Ok, I've used this to create two new branches. 

https://github.com/DLu/navigation/tree/fix357
This uses the getCost function more centrally to fix the places where the factor was not used. 

https://github.com/DLu/navigation/tree/floated_costs
This changes the header of the potential calculator to use floats. 

Do these two changes look to cover your use case?

**Comment by DLu** [comment]
@tavu Likely going to close this if I don't hear back. Also since hydro has since closed up.

**Pull request closed without merging**
