### PR TITLE
not use dynparam to decrease the speed to move, use service call directly

### PR DESCRIPTION
**Pull request by garaemon**
hydro version of https://github.com/ros-planning/navigation/pull/218

### CODE REVIEW

**Comment by efernandez** [comment]
Nice!

**Comment by garaemon** [comment]
updated, please check the latest code.

**Comment by mikeferguson** [comment]
This might have broken the build? http://jenkins.ros.org/job/devel-indigo-navigation/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/15/console

Although it appears maybe the farm might be messed up? It can't seem to install libboost-all-dev?

**Comment by mikeferguson** [comment]
Ok, not a broken build for tests (hydro succeeded http://jenkins.ros.org/job/devel-hydro-navigation/27/)

However, I now notice that move_slow_and_clear does not depend on dynamic_reconfigure -- that should probably be added to both the package.xml and CMakeLists else building debians will fail. @DLu, do you want me to do that?

**Comment by DLu** [comment]
Yes, go ahead.

**Pull request merged**
