### PR TITLE
Switch to tf2 for Jade

### PR DESCRIPTION
**Pull request by vrabaud**
Same as https://github.com/ros-planning/navigation/pull/317 but for Jade.
Honestly, this merge request is only useful because it can free you from PCL later. So you might as well drop the indigo version (you won't gain performance or anything else).

### CODE REVIEW

**Comment by mikeferguson** [comment]
I haven't been following super closely -- are all the required PRs for TF2 now merged and released?

**Comment by vrabaud** [comment]
just rebased again, and it's all good with tf2 from shadow fixed.

**Comment by vrabaud** [comment]
@DLu , any comment on that ? I know it only compiles with tf2 master (a new release should happen soonish) but if you have any prior comment, please let me know (I rebase this MR once in a while).

**Comment by mikeferguson** [comment]
@vrabaud thanks for rebasing (again) -- I'll try to test this out on a robot ASAP

**Comment by mikeferguson** [comment]
And then I realized that running this on a robot is a whole bunch of fun, since this is jade....

**Comment by vrabaud** [comment]
ok, the required changed in tf2 are now in shadow-fixed, feel free to merge whenever.
Please remember that this is the first step to remove the PCL dependency.

**Comment by vrabaud** [comment]
and yet another rebase that is safe to merge for buildfarm compilation.

**Comment by vrabaud** [comment]
and guess who rebased for the new year ? :)

**Comment by vrabaud** [comment]
Closing in favor of https://github.com/ros-planning/navigation/pull/458

**Pull request closed without merging**
