### PR TITLE
Fixes #206 for kinetic

### LINKED ISSUE #206: When using robot_radius, footprint is incorrectly set by costmap2d_ros
When using robot_radius, the footprint gets set by move_base to [] if the footprint parameter is not set. This means that the second time you launch the navigation stack, the footprint will be improper and an error appears:

```
[ERROR] [1402335344.906978220, 66.013000000]: You must specify at least three points for the robot footprint, reverting to previous footprint.
```

My current work around has been to add this to the launch file:

```
<rosparam command="delete" ns="move_base" />
```

### PR DESCRIPTION
**Pull request by DLu**
Version of #343 for Kinetic. Lunar PR pending approval of this one. 

(@commaster90  I can't officially assign you as a reviewer, but please take a quick look)

### CODE REVIEW

**Review by patrickcjh — COMMENTED** [review]
You still need the rest of the changes from #343. Otherwise it will enter the first "if" since the `footprint` parameter was there, and therefore skipping the `radius` parameter.

**Comment by DLu** [comment]
Oh, good point. That look better?

**Comment by mikeferguson** [comment]
LGTM

**Comment by patrickcjh** [comment]
:+1:

**Comment by vpradeep07** [comment]
Thanks for the fix!  I can confirm that upgrading the navigation stack from version `1.14.2` to `1.14.3` resolved the bug mentioned here.

**Pull request merged**
