### PR TITLE
Melodic buildfarm errors

### LINKED ISSUE #722: Compile Error on Melodic
```
22:48:45 [ 74%] Building CXX object CMakeFiles/inflation_tests.dir/test/inflation_tests.cpp.o
22:48:50 /tmp/catkin_workspace/src/navigation/costmap_2d/test/inflation_tests.cpp: In function ‘void validatePointInflation(unsigned int, unsigned int, costmap_2d::Costmap2D*, costmap_2d::InflationLayer*, double)’:
22:48:50 /tmp/catkin_workspace/src/navigation/costmap_2d/test/inflation_tests.cpp:88:52: error: call of overloaded ‘abs(unsigned int)’ is ambiguous
22:48:50          unsigned int dx = abs(cell.x_ - cell.src_x_);
22:48:50                                                     ^
22:48:50 In file included from /usr/include/c++/7/cstdlib:75:0,
22:48:50                  from /usr/include/c++/7/ext/string_conversions.h:41,
22:48:50                  from /usr/include/c++/7/bits/basic_string.h:6349,
22:48:50                  from /usr/include/c++/7/string:52,
22:48:50                  from /usr/include/c++/7/stdexcept:39,
22:48:50                  from /usr/include/c++/7/array:39,
22:48:50                  from /usr/include/c++/7/tuple:39,
22:48:50                  from /usr/include/c++/7/bits/stl_map.h:63,
22:48:50                  from /usr/include/c++/7/map:61,
22:48:50                  from /tmp/catkin_workspace/src/navigation/costmap_2d/test/inflation_tests.cpp:34:
22:48:50 /usr/include/stdlib.h:837:12: note: candidate: int abs(int)
22:48:50  extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
22:48:50             ^~~
22:48:50 In file included from /usr/include/c++/7/cstdlib:77:0,
22:48:50                  from /usr/include/c++/7/ext/string_conversions.h:41,
22:48:50                  from /usr/include/c++/7/bits/basic_string.h:6349,
22:48:50                  from /usr/include/c++/7/string:52,
22:48:50                  from /usr/include/c++/7/stdexcept:39,
22:48:50                  from /usr/include/c++/7/array:39,
22:48:50                  from /usr/include/c++/7/tuple:39,
22:48:50                  from /usr/include/c++/7/bits/stl_map.h:63,
22:48:50                  from /usr/include/c++/7/map:61,
22:48:50                  from /tmp/catkin_workspace/src/navigation/costmap_2d/test/inflation_tests.cpp:34:
22:48:50 /usr/include/c++/7/bits/std_abs.h:56:3: note: candidate: long int std::abs(long int)
22:48:50    abs(long __i) { return __builtin_labs(__i); }
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:61:3: note: candidate: long long int std::abs(long long int)
22:48:50    abs(long long __x) { return __builtin_llabs (__x); }
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:70:3: note: candidate: constexpr double std::abs(double)
22:48:50    abs(double __x)
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:74:3: note: candidate: constexpr float std::abs(float)
22:48:50    abs(float __x)
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:78:3: note: candidate: constexpr long double std::abs(long double)
22:48:50    abs(long double __x)
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:84:3: note: candidate: constexpr __int128 std::abs(__int128)
22:48:50    abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:102:3: note: candidate: constexpr __float128 std::abs(__float128)
22:48:50    abs(__float128 __x)
22:48:50    ^~~
22:48:50 /tmp/catkin_workspace/src/navigation/costmap_2d/test/inflation_tests.cpp:89:52: error: call of overloaded ‘abs(unsigned int)’ is ambiguous
22:48:50          unsigned int dy = abs(cell.y_ - cell.src_y_);
22:48:50                                                     ^
22:48:50 In file included from /usr/include/c++/7/cstdlib:75:0,
22:48:50                  from /usr/include/c++/7/ext/string_conversions.h:41,
22:48:50                  from /usr/include/c++/7/bits/basic_string.h:6349,
22:48:50                  from /usr/include/c++/7/string:52,
22:48:50                  from /usr/include/c++/7/stdexcept:39,
22:48:50                  from /usr/include/c++/7/array:39,
22:48:50                  from /usr/include/c++/7/tuple:39,
22:48:50                  from /usr/include/c++/7/bits/stl_map.h:63,
22:48:50                  from /usr/include/c++/7/map:61,
22:48:50                  from /tmp/catkin_workspace/src/navigation/costmap_2d/test/inflation_tests.cpp:34:
22:48:50 /usr/include/stdlib.h:837:12: note: candidate: int abs(int)
22:48:50  extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
22:48:50             ^~~
22:48:50 In file included from /usr/include/c++/7/cstdlib:77:0,
22:48:50                  from /usr/include/c++/7/ext/string_conversions.h:41,
22:48:50                  from /usr/include/c++/7/bits/basic_string.h:6349,
22:48:50                  from /usr/include/c++/7/string:52,
22:48:50                  from /usr/include/c++/7/stdexcept:39,
22:48:50                  from /usr/include/c++/7/array:39,
22:48:50                  from /usr/include/c++/7/tuple:39,
22:48:50                  from /usr/include/c++/7/bits/stl_map.h:63,
22:48:50                  from /usr/include/c++/7/map:61,
22:48:50                  from /tmp/catkin_workspace/src/navigation/costmap_2d/test/inflation_tests.cpp:34:
22:48:50 /usr/include/c++/7/bits/std_abs.h:56:3: note: candidate: long int std::abs(long int)
22:48:50    abs(long __i) { return __builtin_labs(__i); }
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:61:3: note: candidate: long long int std::abs(long long int)
22:48:50    abs(long long __x) { return __builtin_llabs (__x); }
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:70:3: note: candidate: constexpr double std::abs(double)
22:48:50    abs(double __x)
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:74:3: note: candidate: constexpr float std::abs(float)
22:48:50    abs(float __x)
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:78:3: note: candidate: constexpr long double std::abs(long double)
22:48:50    abs(long double __x)
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:84:3: note: candidate: constexpr __int128 std::abs(__int128)
22:48:50    abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
22:48:50    ^~~
22:48:50 /usr/include/c++/7/bits/std_abs.h:102:3: note: candidate: constexpr __float128 std::abs(__float128)
22:48:50    abs(__float128 __x)
22:48:50    ^~~
22:48:51 make[3]: *** [CMakeFiles/inflation_tests.dir/test/inflation_tests.cpp.o] Error 1
22:48:51 CMakeFiles/inflation_tests.dir/build.make:62: recipe for target 'CMakeFiles/inflation_tests.dir/test/inflation_tests.cpp.o' failed
22:48:51 CMakeFiles/Makefile2:4681: recipe for target 'CMakeFiles/inflation_tests.dir/all' failed
22:48:51 make[2]: *** [CMakeFiles/inflation_tests.dir/all] Error 2
22:48:51 CMakeFiles/Makefile2:3039: recipe for target 'CMakeFiles/tests.dir/rule' failed
22:48:51 make[1]: *** [CMakeFiles/tests.dir/rule] Error 2
22:48:51 Makefile:1189: recipe for target 'tests' failed
22:48:51 make: *** [tests] Error 2
22:48:51 <== Failed to process package 'costmap_2d': 
22:48:51   Command '['/tmp/catkin_workspace/devel_isolated/voxel_grid/env.sh', 'make', '-j1', 'tests']' returned non-zero exit status 2
22:48:51 
22:48:51 Reproduce this error by running:
22:48:51 ==> cd /tmp/catkin_workspace/build_isolated/costmap_2d && /tmp/catkin_workspace/devel_isolated/voxel_grid/env.sh make -j1 tests
22:48:51 
22:48:51 Command failed, exiting.
```

### PR DESCRIPTION
**Pull request by moriarty**
This _should_ fix #722 for at least **bionic**

### CODE REVIEW

**Comment by moriarty** [comment]
This is my local output, there is still a SEVERE WARNING :worried: but the original failing compile error in #722 is fixed.

```
amoriarty at SW44 in ~/melodic/src/navigation/costmap_2d on melodic-buildfarm-errors
$ catkin build --this --catkin-make-args run_tests
...
Starting  >>> costmap_2d                                                                                                                                                                                   
___________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << costmap_2d:make /home/amoriarty/melodic/logs/costmap_2d/build.make.006.log                                                                                                                   
Error:   Index entry for topic /base_scan contains invalid time.  This message will not be loaded.
         at line 633 in /tmp/binarydeb/ros-melodic-rosbag-storage-1.13.6/src/bag.cpp
inflation_tests: /usr/include/boost/thread/pthread/recursive_mutex.hpp:104: boost::recursive_mutex::~recursive_mutex(): Assertion `!pthread_mutex_destroy(&m)' failed.
[FATAL] [1526420371.701817133]: The footprint (parameter /footprint_test/xmlrpc_fail/footprint) must be specified as list of lists on the parameter server eg: [[x1, y1], [x2, y2], ..., [xn, yn]], but this spec is not of that form.
Warning: class_loader.ClassLoader: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
         at line 122 in /tmp/binarydeb/ros-melodic-class-loader-0.4.1/src/class_loader.cpp
cd /home/amoriarty/melodic/build/costmap_2d; catkin build --get-env costmap_2d | catkin env -si  /usr/bin/make run_tests --jobserver-fds=6,7 -j; cd -
...........................................................................................................................................................................................................
Finished  <<< costmap_2d                         [ 44.2 seconds ]                                                                                                                                          
[build] Summary: All 7 packages succeeded!                                                                                                                                                                 
[build]   Ignored:   106 packages were skipped or are blacklisted.                                                                                                                                         
[build]   Warnings:  2 packages succeeded with warnings.                                                                                                                                                   
[build]   Abandoned: None.                                                                                                                                                                                 
[build]   Failed:    None.                                                                                                                                                                                 
[build] Runtime: 1 minute and 56.6 seconds total.      
```

**Comment by mikeferguson** [comment]
That SEVERE WARNING has existed for a while, FYI.

**Comment by moriarty** [comment]
Now it's failing while running the rostests on buildfarm, but not locally for me.

**buildfarm:**
```
15:16:22 -- run_tests.py: verify result "/tmp/catkin_workspace/test_results/costmap_2d/rostest-test_static_tests.xml"
15:16:22 [100%] Built target _run_tests_costmap_2d_rostest_test_static_tests.launch
15:16:22 Scanning dependencies of target _run_tests_costmap_2d_rostest_test_footprint_tests.launch
15:16:22 -- run_tests.py: execute commands
15:16:22   /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/tmp/catkin_workspace/src/navigation/costmap_2d --package=costmap_2d --results-filename test_footprint_tests.xml --results-base-dir "/tmp/catkin_workspace/test_results" /tmp/catkin_workspace/src/navigation/costmap_2d/test/footprint_tests.launch 
15:16:22 ... logging to /home/buildfarm/.ros/log/rostest-7dbceb2bd5ee-22794.log
15:16:22 [ROSUNIT] Outputting test results to /tmp/catkin_workspace/test_results/costmap_2d/rostest-test_footprint_tests.xml
15:16:23 Error:   TF_NAN_INPUT: Ignoring transform for child_frame_id "base_link" from authority "default_authority" because of a nan value in the transform (0.000000 0.000000 0.000000) (-nan -0.000000 -0.000000 0.500000)
15:16:23          at line 244 in /tmp/binarydeb/ros-melodic-tf2-0.6.2/src/buffer_core.cpp
15:16:23 Error:   TF_DENORMALIZED_QUATERNION: Ignoring transform for child_frame_id "base_link" from authority "default_authority" because of an invalid quaternion in the transform (-nan -0.000000 -0.000000 0.500000)
15:16:23          at line 257 in /tmp/binarydeb/ros-melodic-tf2-0.6.2/src/buffer_core.cpp
15:16:33 [Testcase: testfootprint_test] ... ERROR!
15:16:33 ERROR: max time [10.0s] allotted for test [footprint_test] of type [costmap_2d/footprint_tests]
15:16:33   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
15:16:33     testMethod()
15:16:33   File "/opt/ros/melodic/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
15:16:33     self.test_parent.run_test(test)
15:16:33   File "/opt/ros/melodic/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
15:16:33     return self.runner.run_test(test)
15:16:33   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/launch.py", line 689, in run_test
15:16:33     (test.time_limit, test.test_name, test.package, test.type))
15:16:33 --------------------------------------------------------------------------------
15:16:33 
15:16:33 [ROSTEST]-----------------------------------------------------------------------
15:16:33 
15:16:33 
15:16:33 SUMMARY
15:16:33 [1;31m * RESULT: FAIL[0m
15:16:33  * TESTS: 0
15:16:33 [1;31m * ERRORS: 1[0m
15:16:33  * FAILURES: 0
```

**local:**
```
amoriarty at SW44 in ~/melodic/src/navigation on melodic-buildfarm-errors
$ /opt/ros/melodic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/amoriarty/melodic/src/navigation/costmap_2d --package=costmap_2d --results-filename=test_footprint_test.xml --results-base-dir "/home/amoriarty/melodic/test_results" /home/amoriarty/melodic/src/navigation/costmap_2d/test/footprint_tests.launch 
... logging to /home/amoriarty/.ros/log/rostest-SW44-25506.log
[ROSUNIT] Outputting test results to /home/amoriarty/melodic/test_results/costmap_2d/rostest-test_footprint_test.xml
[FATAL] [1526423396.559754662]: The footprint (parameter /footprint_test/xmlrpc_fail/footprint) must be specified as list of lists on the parameter server eg: [[x1, y1], [x2, y2], ..., [xn, yn]], but this spec is not of that form.
Warning: class_loader.ClassLoader: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
         at line 122 in /tmp/binarydeb/ros-melodic-class-loader-0.4.1/src/class_loader.cpp
[Testcase: testfootprint_test] ... ok

[ROSTEST]-----------------------------------------------------------------------

[costmap_2d.rosunit-footprint_test/unpadded_footprint_from_string_param][passed]
[costmap_2d.rosunit-footprint_test/padded_footprint_from_string_param][passed]
[costmap_2d.rosunit-footprint_test/radius_param][passed]
[costmap_2d.rosunit-footprint_test/footprint_from_xmlrpc_param][passed]
[costmap_2d.rosunit-footprint_test/footprint_from_same_level_param][passed]
[costmap_2d.rosunit-footprint_test/footprint_from_xmlrpc_param_failure][passed]
[costmap_2d.rosunit-footprint_test/footprint_empty][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 7
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/amoriarty/.ros/log/rostest-SW44-25506.log
```

**Comment by moriarty** [comment]
I'm unable to reproduce this locally :man_shrugging: I just added a commit to re-run the test.

**Comment by moriarty** [comment]
@mikeferguson, although I wasn’t able to reproduce the NaN error locally... the commit I added was my best guess at where it could be coming from.

**Comment by mikeferguson** [comment]
You apparently guessed well! Thanks!

**Pull request merged**
